### ISSUE TITLE
re-encode files in utf8

### ISSUE THREAD

**Issue by kapilt** [jtroberts83/Cloud-Custodian#3]
alot of the files here are encoded in utf-16 which means they display poorly on other systems. i'd suggest saving them in utf8
```
 $ file Policies/global/global-s3-policies.yaml 
Policies/global/global-s3-policies.yaml: Little-endian UTF-16 Unicode text, with CRLF, CR line terminators
```

**Comment by kapilt** [comment]
![screen shot 2018-10-04 at 5 19 35 pm](https://user-images.githubusercontent.com/21650/46503734-b313bf00-c7f9-11e8-869e-04abda54d611.png)

example of trying to view the file in less or nano

**Comment by jtroberts83** [comment]
I deleted the policy files as they were old and outdated and as you mentioned were encoded oddly
